version: '3'
services:
  gms_db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"

    volumes:
      - dbdata:/var/lib/mysql

  gms_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - gms_db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:

